data <- read.table("household_power_consumption.txt",sep = ";",na.strings = "?",header = TRUE)
data1 <- subset(data,IDate %in% c("1/2/2007","2/2/2007"))
png("plot1.png")
hist(data1$Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()